"""tareas modified

Revision ID: 480acbdf4b01
Revises: 467e3e5e1377
Create Date: 2021-06-09 16:11:59.324320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480acbdf4b01'
down_revision = '467e3e5e1377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarea', sa.Column('titulo', sa.String(length=150), nullable=True))
    op.add_column('tarea', sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True))
    op.add_column('tarea', sa.Column('fecha_de_entrega', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarea', 'fecha_de_entrega')
    op.drop_column('tarea', 'fecha_de_creacion')
    op.drop_column('tarea', 'titulo')
    # ### end Alembic commands ###
