"""Calificaciones added

Revision ID: 80febbe9446e
Revises: 480acbdf4b01
Create Date: 2021-06-11 15:31:46.781210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80febbe9446e'
down_revision = '480acbdf4b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('id_alumno', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calificaciones')
    # ### end Alembic commands ###
